default:
  image: mitchh/ruby-node-yarn-chrome-chromedriver:3.0.3

.bundle_install: &bundle_install
  - bundle check || bundle install --deployment --jobs=4 --retry=3 --without deploy development doc production --path vendor/ruby

.yarn_install: &yarn_install
  - yarn install --cache-folder .yarn-cache/



cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/ruby
  key:
    files:
      - yarn.lock
  paths:
    - .yarn-cache/

stages:
  - build
  - test
  - deploy

build:
  before_script:
    - bundle config set path 'vendor/ruby'
  stage: build
  script:
    - *bundle_install
    - *yarn_install
    - bundle exec rake login:deploy_json

test:
  before_script:
    - bundle config set path 'vendor/ruby'
  stage: test
  script:
    - *bundle_install
    - *yarn_install
    - make test
  artifacts:
    paths:
      - /tmp/test-results

deploy:
  image: 18fgsa/cloud-foundry-cli
  stage: deploy
  script:
    - cf -v
    - bundle exec rake login:deploy_json
    - cf login -a https://api.fr.cloud.gov -u "4fbf18ec-1497-433f-814f-8c175041a6f1" -p $CF_PASS -o "gsa-login-prototyping" -s "$SPACE"
    - cf push $SPACE-identity-oidc-sinatra
  parallel:
    matrix:
      - SPACE: [prod, staging, int, dev, dm]

# Sync from GitHub
include:
  project: 'lg/identity-gitlab'
  ref: 'main'
  file: '.gitlab-ci-sync.yml'
