bundler_args: "--deployment --jobs=3 --retry=3 --without deploy development doc production"
cache: bundler
language: ruby
matrix:
  fast_finish: true
notifications:
  email: false
rvm:
  - ruby-2.3.3
sudo: false
script:
  - make test
