# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

executors:
  ruby_browsers:
    docker:
      - image: cimg/ruby:3.0.4-browsers
        environment:
          BUNDLER_VERSION: 2.3.13

commands:
  bundle-yarn-install:
    steps:
      - restore_cache:
          key: identity-oidc-bundle-{{ checksum "Gemfile.lock" }}
      - run: gem install bundler --version $BUNDLER_VERSION
      - run:
          name: Install dependencies
          command: |
            bundle check || bundle install --deployment --jobs=4 --retry=3 \
              --without deploy development doc production --path vendor/bundle
      - save_cache:
          key: identity-oidc-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          key: identity-oidc-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Yarn
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: identity-oidc-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  build-release:
    steps:
      - run:
          name: Create deploy.json
          command: bundle exec rake login:deploy_json
      - run:
          name: Copy vendor dependencies
          command: make copy_vendor

jobs:
  build:
    executor: ruby_browsers
    working_directory: ~/identity-oidc-sinatra
    steps:
      - checkout

      - bundle-yarn-install

      - build-release

      - run:
          name: Copy example environment
          command: make .env

      - run:
          name: Run Tests
          command: |
            make test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy:
    executor: ruby_browsers
    working_directory: ~/identity-oidc-sinatra
    parameters:
      space:
        type: string
    steps:
      - checkout

      - bundle-yarn-install

      - build-release

      - run:
          name: Install cf cli
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v

      - run:
          name: login to cloud.gov
          command: |
            cf login -a https://api.fr.cloud.gov -u "4fbf18ec-1497-433f-814f-8c175041a6f1" -p $CF_PASS -o "gsa-login-prototyping" -s "<< parameters.space >>"

      - run:
          name: deploy to cloud.gov
          command: |
            cf push << parameters.space >>-identity-oidc-sinatra

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
          matrix:
            parameters:
              space:
                - prod
                - staging
                - int
                - dev
                - dm
