# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the Ruby version you desire here
      - image: circleci/ruby:2.6.5

    working_directory: ~/identity-oidc-sinatra
    steps:
      - checkout

      - restore-cache:
          key: identity-oidc-sinatra-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --deployment --jobs=4 --retry=3 --without deploy development doc production --path vendor/bundle
            cp .env.example .env
            bundle exec rake login:deploy_json

      # Store bundle cache
      - save-cache:
          key: identity-oidc-sinatra-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Tests
          command: |
            make test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/identity-oidc-sinatra
    steps:
      - checkout

      - restore_cache:
          key: identity-oidc-sinatra-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --deployment --jobs=4 --retry=3 --without deploy development doc production --path vendor/bundle
            bundle exec rake login:deploy_json

      - run:
          name: Install cf cli
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v

      - run:
          name: login to cloud.gov
          command: |
            cf login -a https://api.fr.cloud.gov -u "4fbf18ec-1497-433f-814f-8c175041a6f1" -p $CF_PASS -o "gsa-login-prototyping" -s "int"

      - run:
          name: deploy to cloud.gov
          command: |
            cf push int-identity-oidc-sinatra

      - save_cache:
          key: identity-oidc-sinatra-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
