# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the Ruby version you desire here
      - image: circleci/ruby:2.3.3

    working_directory: ~/identity-openidconnect-sinatra
    steps:
      - checkout

      - restore-cache:
          key: identity-openidconnect-sinatra-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --deployment --jobs=4 --retry=3 --without deploy development doc production --path vendor/bundle

      # Store bundle cache
      - save-cache:
          key: identity-openidconnect-sinatra-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Tests
          command: |
            make test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
